// Generates app/src/main/kotlin/com/tankobun/app/TankobunPalettes.kt from themes.json.
//
// Each theme is a seed color plus explicit secondary, tertiary and neutral hues. The tonal
// palettes come from Material Color Utilities, so every Material 3 role (including the
// surfaceContainer family) is filled and keeps its contrast guarantees. Dark primaries can
// use a brighter tone than the Material default to keep each theme recognizable at night.
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  DynamicScheme,
  Hct,
  MaterialDynamicColors,
  SchemeMonochrome,
  TonalPalette,
  argbFromHex,
  hexFromArgb,
} from '@material/material-color-utilities';
import { Variant } from './node_modules/@material/material-color-utilities/dynamiccolor/variant.js';

const here = dirname(fileURLToPath(import.meta.url));
const output = resolve(here, '../../app/src/main/kotlin/com/tankobun/app/TankobunPalettes.kt');
const themes = JSON.parse(readFileSync(resolve(here, 'themes.json'), 'utf8'));

const roles = [
  'primary', 'onPrimary', 'primaryContainer', 'onPrimaryContainer', 'inversePrimary',
  'secondary', 'onSecondary', 'secondaryContainer', 'onSecondaryContainer',
  'tertiary', 'onTertiary', 'tertiaryContainer', 'onTertiaryContainer',
  'background', 'onBackground', 'surface', 'onSurface', 'surfaceVariant', 'onSurfaceVariant',
  'surfaceTint', 'inverseSurface', 'inverseOnSurface',
  'error', 'onError', 'errorContainer', 'onErrorContainer',
  'outline', 'outlineVariant', 'scrim',
  'surfaceBright', 'surfaceContainer', 'surfaceContainerHigh', 'surfaceContainerHighest',
  'surfaceContainerLow', 'surfaceContainerLowest', 'surfaceDim',
];

const hue = (hex) => Hct.fromInt(argbFromHex(hex)).hue;

function scheme(theme, dark) {
  const seed = argbFromHex(theme.seed);
  if (theme.monochrome) return { scheme: new SchemeMonochrome(Hct.fromInt(seed), dark, 0) };
  const seedHct = Hct.fromInt(seed);
  const neutral = theme.neutral ?? theme.seed;
  const neutralChroma = theme.neutralChroma ?? 6;
  const palettes = {
    primary: TonalPalette.fromHueAndChroma(seedHct.hue, Math.max(seedHct.chroma, theme.primaryChroma ?? 48)),
    secondary: TonalPalette.fromHueAndChroma(hue(theme.secondary ?? theme.seed), theme.secondaryChroma ?? 16),
    tertiary: TonalPalette.fromHueAndChroma(hue(theme.tertiary), theme.tertiaryChroma ?? 24),
    neutral: TonalPalette.fromHueAndChroma(hue(neutral), neutralChroma),
    neutralVariant: TonalPalette.fromHueAndChroma(hue(neutral), neutralChroma + 4),
  };
  return {
    palettes,
    scheme: new DynamicScheme({
      sourceColorArgb: seed,
      variant: Variant.TONAL_SPOT,
      contrastLevel: 0,
      isDark: dark,
      primaryPalette: palettes.primary,
      secondaryPalette: palettes.secondary,
      tertiaryPalette: palettes.tertiary,
      neutralPalette: palettes.neutral,
      neutralVariantPalette: palettes.neutralVariant,
    }),
  };
}

function colors(theme, dark) {
  const { scheme: s, palettes } = scheme(theme, dark);
  const values = {};
  for (const role of roles) {
    const color = MaterialDynamicColors[role === 'surfaceTint' ? 'primary' : role];
    values[role] = hexFromArgb(color.getArgb(s)).slice(1).toUpperCase();
  }
  if (theme.monochrome && !dark) values.onPrimary = 'FFFFFF';
  if (palettes && dark && theme.darkPrimaryTone) {
    values.primary = hexFromArgb(palettes.primary.tone(theme.darkPrimaryTone)).slice(1).toUpperCase();
    values.onPrimary = hexFromArgb(palettes.primary.tone(10)).slice(1).toUpperCase();
    values.surfaceTint = values.primary;
  }
  if (palettes && dark && theme.darkSecondaryTone) {
    values.secondary = hexFromArgb(palettes.secondary.tone(theme.darkSecondaryTone)).slice(1).toUpperCase();
    values.onSecondary = hexFromArgb(palettes.secondary.tone(10)).slice(1).toUpperCase();
  }
  return values;
}

const pascal = (id) => id.charAt(0) + id.slice(1).toLowerCase();
let body = '';
for (const theme of themes) {
  for (const dark of [false, true]) {
    const values = colors(theme, dark);
    const name = `${pascal(theme.id)}${dark ? 'Dark' : 'Light'}`;
    body += `\nprivate val ${name}: ColorScheme = ${dark ? 'darkColorScheme' : 'lightColorScheme'}(\n`;
    for (const role of roles) body += `    ${role} = Color(0xFF${values[role]}),\n`;
    body += ')\n';
  }
}

const cases = themes
  .map((t) => `    TankobunPaletteId.${t.id} -> if (dark) ${pascal(t.id)}Dark else ${pascal(t.id)}Light`)
  .join('\n');

const kotlin = `// Generated by tools/theme-palettes/generate.mjs from themes.json. Do not edit by hand.
package com.tankobun.app

import androidx.compose.material3.ColorScheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

internal fun generatedColorScheme(palette: TankobunPaletteId, dark: Boolean): ColorScheme? = when (palette) {
${cases}
    else -> null
}
${body}`;

writeFileSync(output, kotlin);
console.log(`Wrote ${output}`);
